defmodule PgFlow.Test.UpstreamFixture.CoreMigration do
  @moduledoc false
  use Ecto.Migration

  @doc "Installs the frozen core baseline for upgrade tests."
  def up, do: PgFlow.Migration.up(version: 1)
  @doc "Uninstalls the core baseline from a disposable fixture."
  def down, do: PgFlow.Migration.down(version: 0)
end

defmodule PgFlow.Test.UpstreamFixture.HelpersMigration do
  @moduledoc false
  use Ecto.Migration

  @doc "Installs the released helpers baseline for upgrade tests."
  def up, do: PgFlow.HelpersMigration.up(version: 4)
  @doc "Uninstalls helpers from a disposable fixture."
  def down, do: PgFlow.HelpersMigration.down(version: 0)
end

defmodule PgFlow.Test.UpstreamFixture do
  @moduledoc """
  Creates disposable databases for upstream compatibility and upgrade tests.

  Every database name is generated by this module and checked again during
  teardown. The administrative connection must target a database other than
  the ordinary application test database.
  """

  alias EctoEvolver.Adapters.Postgres, as: EvolverPostgres
  alias PgFlow.Test.UpstreamFixture.{CoreMigration, HelpersMigration}

  @database_prefix "pgflow_upstream_fixture_"
  @manifest_path Path.expand("manifest.json", __DIR__)

  @enforce_keys [
    :admin_url,
    :application_database,
    :database,
    :database_url,
    :names,
    :repo_name,
    :repo_pid,
    :runs,
    :versions
  ]
  defstruct @enforce_keys

  @type t :: %__MODULE__{
          admin_url: String.t(),
          application_database: String.t(),
          database: String.t(),
          database_url: String.t(),
          names: map(),
          repo_name: atom(),
          repo_pid: pid(),
          runs: map(),
          versions: %{core: non_neg_integer(), helpers: non_neg_integer()}
        }

  @doc """
  Creates a uniquely named database, installs core V01 and helpers V04, and
  seeds representative pre-upgrade data.

  The `:admin_url` option defaults to `PGFLOW_UPSTREAM_ADMIN_URL`, then to the
  local test Postgres administrative database.
  """
  @spec setup!(keyword()) :: t()
  def setup!(opts \\ []) do
    admin_url = Keyword.get(opts, :admin_url, default_admin_url())
    application_database = application_database()
    refuse_application_database!(admin_url, application_database)

    suffix = :crypto.strong_rand_bytes(16) |> Base.encode16(case: :lower)
    database = @database_prefix <> suffix
    database_url = replace_database(admin_url, database)
    repo_name = :"pgflow_upstream_fixture_repo_#{suffix}"

    admin_query!(admin_url, "CREATE DATABASE #{quote_identifier(database)}")

    repo_pid =
      case PgFlow.TestRepo.start_link(
             name: repo_name,
             url: database_url,
             pool: DBConnection.ConnectionPool,
             pool_size: 2
           ) do
        {:ok, pid} ->
          pid

        {:error, reason} ->
          drop_database(admin_url, database)
          raise "could not start upstream fixture repository: #{inspect(reason)}"
      end

    fixture = %__MODULE__{
      admin_url: admin_url,
      application_database: application_database,
      database: database,
      database_url: database_url,
      names: fixture_names(String.slice(suffix, 0, 16)),
      repo_name: repo_name,
      repo_pid: repo_pid,
      runs: %{},
      versions: %{core: 0, helpers: 0}
    }

    try do
      installed_fixture = install!(fixture)
      Process.unlink(repo_pid)
      installed_fixture
    rescue
      exception ->
        if Process.alive?(repo_pid), do: Supervisor.stop(repo_pid)
        drop_database(admin_url, database)
        reraise exception, __STACKTRACE__
    end
  end

  @doc "Stops the fixture repository and drops only its generated database."
  @spec teardown!(t()) :: :ok
  def teardown!(%__MODULE__{} = fixture) do
    ensure_owned_database!(fixture.database)

    if Process.alive?(fixture.repo_pid) do
      Supervisor.stop(fixture.repo_pid)
    end

    drop_database(fixture.admin_url, fixture.database)
  end

  @doc "Returns the ordinary test repository URL from application configuration."
  @spec application_database_url() :: String.t()
  def application_database_url do
    config = Application.fetch_env!(:pgflow, PgFlow.TestRepo)

    username = URI.encode_www_form(config[:username])
    password = URI.encode_www_form(config[:password])
    database = URI.encode_www_form(config[:database])

    URI.to_string(
      URI.new!(
        "postgres://#{username}:#{password}@#{config[:hostname]}:#{config[:port]}/#{database}"
      )
    )
  end

  @doc "Returns whether a database exists through the dedicated administrative connection."
  @spec database_exists?(String.t(), String.t()) :: boolean()
  def database_exists?(admin_url, database) do
    %{rows: [[exists?]]} =
      admin_query!(admin_url, "SELECT EXISTS(SELECT 1 FROM pg_database WHERE datname = $1)", [
        database
      ])

    exists?
  end

  @doc "Executes SQL against a fixture and returns result rows."
  @spec query_rows!(t(), String.t(), list()) :: list(list())
  def query_rows!(fixture, sql, params \\ []) do
    with_fixture_repo(fixture, fn ->
      %{rows: rows} = PgFlow.TestRepo.query!(sql, params)
      rows
    end)
  end

  @doc "Loads the checked-in compatibility fixture manifest."
  @spec manifest() :: map()
  def manifest do
    @manifest_path
    |> File.read!()
    |> Jason.decode!()
  end

  @doc "Returns the default administrative Postgres URL for disposable fixture databases."
  @spec default_admin_url() :: String.t()
  def default_admin_url do
    System.get_env(
      "PGFLOW_UPSTREAM_ADMIN_URL",
      replace_database(application_database_url(), "postgres")
    )
  end

  @doc "Returns the configured ordinary application test database name."
  @spec application_database_name() :: String.t()
  def application_database_name, do: application_database()

  @doc "Returns whether a database name is owned by upstream compatibility fixtures."
  @spec fixture_database?(String.t()) :: boolean()
  def fixture_database?(database) do
    manifest()["harness"]["database_prefixes"]
    |> Enum.any?(&String.starts_with?(database, &1))
  end

  defp install!(fixture) do
    with_fixture_repo(fixture, fn ->
      PgFlow.TestRepo.query!("CREATE EXTENSION IF NOT EXISTS pgmq")

      Ecto.Migrator.up(PgFlow.TestRepo, 9_000_000_001, CoreMigration, log: false)
      Ecto.Migrator.up(PgFlow.TestRepo, 9_000_000_002, HelpersMigration, log: false)

      install_realtime_shim!()
      runs = seed!(fixture.names)

      versions = %{
        core:
          EvolverPostgres.get_version(
            PgFlow.TestRepo,
            "pgflow",
            {:view, "pgflow_version"}
          ),
        helpers:
          EvolverPostgres.get_version(
            PgFlow.TestRepo,
            "pgflow",
            {:view, "extensions_version"}
          )
      }

      expected = manifest()["baseline"]

      unless versions == %{
               core: expected["core_version"],
               helpers: expected["helpers_version"]
             } do
        raise "fixture installed unexpected pgflow versions: #{inspect(versions)}"
      end

      %{fixture | runs: runs, versions: versions}
    end)
  end

  defp install_realtime_shim! do
    PgFlow.TestRepo.query!("CREATE SCHEMA IF NOT EXISTS realtime")

    PgFlow.TestRepo.query!("""
    CREATE TABLE IF NOT EXISTS realtime.messages (
      id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
      topic text,
      event text,
      payload jsonb,
      private boolean DEFAULT false,
      inserted_at timestamptz DEFAULT now()
    )
    """)

    PgFlow.TestRepo.query!("""
    CREATE OR REPLACE FUNCTION realtime.send(
      payload jsonb, event text, topic text, private boolean DEFAULT false
    ) RETURNS void AS $$
      INSERT INTO realtime.messages (topic, event, payload, private)
      VALUES (topic, event, payload, private);
    $$ LANGUAGE sql
    """)
  end

  defp seed!(names) do
    queued = create_run!(names.queued_flow, "single", "{}")
    started = create_run!(names.started_flow, "single", "{}")
    completed = create_run!(names.completed_flow, "single", "{}")
    failed = create_run!(names.failed_flow, "single", "{}")
    map = create_run!(names.map_flow, "map", "[1,2]")

    create_flow!(names.job_flow)

    PgFlow.TestRepo.query!("UPDATE pgflow.flows SET flow_type = 'job' WHERE flow_slug = $1", [
      names.job_flow
    ])

    create_flow!(names.mixed_case_flow)

    PgFlow.TestRepo.query!(
      """
      UPDATE pgflow.step_tasks
      SET status = 'started', started_at = now(), attempts_count = 1
      WHERE run_id = $1
      """,
      [started]
    )

    PgFlow.TestRepo.query!(
      """
      UPDATE pgflow.step_tasks
      SET status = 'completed', completed_at = now(), output = '{}'::jsonb
      WHERE run_id = $1
      """,
      [completed]
    )

    PgFlow.TestRepo.query!(
      """
      UPDATE pgflow.step_states
      SET status = 'completed', remaining_tasks = 0, completed_at = now(), output = '{}'::jsonb
      WHERE run_id = $1
      """,
      [completed]
    )

    PgFlow.TestRepo.query!(
      """
      UPDATE pgflow.runs
      SET status = 'completed', remaining_steps = 0, completed_at = now(), output = '{}'::jsonb
      WHERE run_id = $1
      """,
      [completed]
    )

    PgFlow.TestRepo.query!(
      """
      UPDATE pgflow.step_tasks
      SET status = 'failed', failed_at = now(), error_message = 'fixture failure'
      WHERE run_id = $1
      """,
      [failed]
    )

    PgFlow.TestRepo.query!(
      "UPDATE pgflow.step_states SET status = 'failed', failed_at = now() WHERE run_id = $1",
      [failed]
    )

    PgFlow.TestRepo.query!(
      "UPDATE pgflow.runs SET status = 'failed', failed_at = now() WHERE run_id = $1",
      [failed]
    )

    PgFlow.TestRepo.query!(
      """
      INSERT INTO pgflow.step_tasks (flow_slug, run_id, step_slug, task_index, message_id)
      VALUES ($1, $2, 'fixture_step', 99, NULL)
      """,
      [names.map_flow, map]
    )

    %{queued: queued, started: started, completed: completed, failed: failed, map: map}
  end

  defp create_run!(flow_slug, step_type, input) do
    create_flow!(flow_slug)

    PgFlow.TestRepo.query!(
      "SELECT pgflow.add_step($1, 'fixture_step', step_type => $2)",
      [flow_slug, step_type]
    )

    %{rows: [[run_id]]} =
      PgFlow.TestRepo.query!(
        "SELECT run_id FROM pgflow.start_flow($1, $2)",
        [flow_slug, Jason.decode!(input)]
      )

    run_id
  end

  defp create_flow!(flow_slug) do
    PgFlow.TestRepo.query!("SELECT pgflow.create_flow($1)", [flow_slug])
  end

  defp fixture_names(suffix) do
    %{
      queued_flow: "fixture_queued_#{suffix}",
      started_flow: "fixture_started_#{suffix}",
      completed_flow: "fixture_completed_#{suffix}",
      failed_flow: "fixture_failed_#{suffix}",
      job_flow: "fixture_job_#{suffix}",
      map_flow: "fixture_map_#{suffix}",
      mixed_case_flow: "FixtureMixedCase#{suffix}"
    }
  end

  defp with_fixture_repo(fixture, fun) do
    previous = PgFlow.TestRepo.put_dynamic_repo(fixture.repo_name)

    try do
      fun.()
    after
      PgFlow.TestRepo.put_dynamic_repo(previous)
    end
  end

  defp application_database do
    Application.fetch_env!(:pgflow, PgFlow.TestRepo)
    |> Keyword.fetch!(:database)
  end

  defp refuse_application_database!(admin_url, application_database) do
    if database_from_url(admin_url) == application_database do
      raise ArgumentError,
            "upstream fixture admin_url points at the ordinary test database #{inspect(application_database)}"
    end
  end

  defp database_from_url(url) do
    url
    |> URI.parse()
    |> Map.fetch!(:path)
    |> String.trim_leading("/")
  end

  defp replace_database(url, database) do
    url
    |> URI.parse()
    |> Map.put(:path, "/#{database}")
    |> URI.to_string()
  end

  defp ensure_owned_database!(database) do
    unless String.starts_with?(database, @database_prefix) do
      raise ArgumentError,
            "refusing to drop database not owned by upstream fixture: #{inspect(database)}"
    end
  end

  defp quote_identifier(identifier) do
    ~s("#{String.replace(identifier, ~s("), ~s(""))}")
  end

  defp drop_database(admin_url, database) do
    ensure_owned_database!(database)

    admin_query!(
      admin_url,
      "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = $1 AND pid <> pg_backend_pid()",
      [database]
    )

    admin_query!(admin_url, "DROP DATABASE IF EXISTS #{quote_identifier(database)}")
    :ok
  end

  defp admin_query!(admin_url, sql, params \\ []) do
    {:ok, connection} = Postgrex.start_link(postgrex_options(admin_url))

    try do
      Postgrex.query!(connection, sql, params)
    after
      GenServer.stop(connection)
    end
  end

  defp postgrex_options(url) do
    uri = URI.parse(url)
    [username, password] = String.split(uri.userinfo || "", ":", parts: 2)

    [
      hostname: uri.host,
      port: uri.port || 5432,
      username: URI.decode(username),
      password: URI.decode(password),
      database: database_from_url(url)
    ]
  end
end
