defmodule Mix.Tasks.Pgflow.Gen.ExtensionsMigration do
  @shortdoc "Generates the required migration for PgFlow extension SQL functions"

  @moduledoc """
  Generates an Ecto migration that installs PgFlow's extension SQL functions.

  ## Usage

      mix pgflow.gen.extensions_migration
      mix pgflow.gen.extensions_migration --migrations-path priv/repo/migrations

  ## Options

    * `--migrations-path` - Path to the migrations directory.
      Defaults to `priv/repo/migrations`.

  ## Generated Functions

  This migration creates PostgreSQL functions in the `pgflow` schema:

  ### Read Functions
    * `get_flow_input(uuid)` - Get flow run input data
    * `flow_exists(text)` - Check if flow exists
    * `get_step_output(uuid, text)` - Get step output

  ### Write Functions
    * `register_worker(uuid, text, text)` - Register or heartbeat a worker
    * `mark_worker_stopped(uuid)` - Mark worker as stopped
    * `recover_stalled_tasks(double precision)` - Recover stalled tasks

  ## Requirements

  The pgflow schema must already exist. Run pgflow migrations first if needed.

  ## Example

      # Generate the migration
      $ mix pgflow.gen.extensions_migration

      # Run the migration
      $ mix ecto.migrate

  """

  use Mix.Task

  @impl Mix.Task
  def run(args) do
    {opts, _, _} =
      OptionParser.parse(args,
        switches: [migrations_path: :string],
        aliases: [p: :migrations_path]
      )

    generate_migration(opts)
  end

  defp generate_migration(opts) do
    migrations_path = Keyword.get(opts, :migrations_path, "priv/repo/migrations")
    File.mkdir_p!(migrations_path)

    timestamp = generate_timestamp()
    app_module = get_app_module()
    migration_content = generate_migration_content(app_module)

    filename = "#{timestamp}_add_pgflow_extensions.exs"
    filepath = Path.join(migrations_path, filename)

    File.write!(filepath, migration_content)

    Mix.shell().info("""
    Generated migration: #{filepath}

    Run the migration with:
        mix ecto.migrate

    This will create PostgreSQL functions in the pgflow schema for:
      - Worker registration and lifecycle
      - Flow input/output queries
      - Stalled task recovery

    Note: The pgflow schema must already exist. Run pgflow migrations first if needed.
    """)
  end

  defp generate_migration_content(app_module) do
    """
    defmodule #{app_module}.Repo.Migrations.AddPgflowExtensions do
      @moduledoc \"\"\"
      Installs PgFlow extension SQL functions in the pgflow schema.

      Generated by: mix pgflow.gen.extensions_migration
      \"\"\"
      use Ecto.Migration

      def up do
        PgFlow.ExtensionsMigration.up()
      end

      def down do
        PgFlow.ExtensionsMigration.down()
      end
    end
    """
  end

  defp get_app_module do
    case Mix.Project.config()[:app] do
      nil ->
        Mix.raise("Could not determine app name from Mix.Project")

      app ->
        app |> to_string() |> Macro.camelize()
    end
  end

  defp generate_timestamp do
    {{year, month, day}, {hour, minute, second}} = :calendar.universal_time()

    :io_lib.format("~4..0B~2..0B~2..0B~2..0B~2..0B~2..0B", [
      year,
      month,
      day,
      hour,
      minute,
      second
    ])
    |> IO.iodata_to_binary()
  end
end
