defmodule Mix.Tasks.PgflowDemo.Test.Setup do
  @moduledoc """
  Prepares the demo test database on shared Postgres clusters.

  When `cron.database_name` points at another database (for example after
  `mix pgflow.test.setup`), the committed `install_extensions` and cleanup
  job migrations cannot be replayed verbatim on `pgflow_demo_dev`. This task
  installs the required extensions, stamps the historical migrations that
  depend on pg_cron, and runs the remaining committed migrations.
  """
  use Mix.Task

  alias __MODULE__.StampMigration
  alias Ecto.Adapters.SQL
  alias PgflowDemo.Jobs.ArticleFlowCleanup

  @extensions_version 20_260_423_202_240
  @cleanup_version 20_260_423_202_249
  @article_flow_version 20_260_423_202_248
  @migrations_path "priv/repo/migrations"
  @shortdoc "Prepare the demo test database for ExUnit"

  @impl Mix.Task
  def run(_args) do
    Mix.Task.run("app.config")
    start_repo!()

    repo = PgflowDemo.Repo
    create_database!(repo)
    ensure_baseline_extensions!(repo)
    stamp_if_needed!(repo, @extensions_version)

    Ecto.Migrator.run(repo, @migrations_path, :up, to: @article_flow_version)

    unless pg_cron_allowed?(repo) do
      ensure_cleanup_job!(repo)
      stamp_if_needed!(repo, @cleanup_version)
    end

    Ecto.Migrator.run(repo, @migrations_path, :up, all: true)
    stop_repo!()
  end

  defp stop_repo! do
    if pid = Process.whereis(PgflowDemo.Repo) do
      Supervisor.stop(pid)
    end
  end

  defp start_repo! do
    for app <- [:crypto, :ssl, :postgrex, :ecto, :ecto_sql, :jason] do
      Application.ensure_all_started(app)
    end

    unless Process.whereis(PgflowDemo.Repo) do
      {:ok, _} = PgflowDemo.Repo.start_link()
    end
  end

  defp create_database!(repo) do
    config = repo.config()
    database = Keyword.fetch!(config, :database)

    admin_config =
      config
      |> Keyword.put(:database, "postgres")
      |> Keyword.put(:pool_size, 1)
      |> Keyword.put(:pool, DBConnection.ConnectionPool)

    {:ok, conn} = Postgrex.start_link(admin_config)

    try do
      case Postgrex.query(conn, "SELECT 1 FROM pg_database WHERE datname = $1", [database]) do
        {:ok, %{rows: []}} ->
          Postgrex.query!(conn, "CREATE DATABASE \"#{database}\"", [])

        {:ok, _} ->
          :ok
      end
    after
      GenServer.stop(conn)
    end
  end

  defp ensure_baseline_extensions!(repo) do
    for statement <- [
          "CREATE EXTENSION IF NOT EXISTS citext",
          "CREATE EXTENSION IF NOT EXISTS pg_trgm",
          "CREATE EXTENSION IF NOT EXISTS pgcrypto"
        ] do
      repo.query!(statement)
    end

    if pg_cron_allowed?(repo) do
      repo.query!("CREATE EXTENSION IF NOT EXISTS pg_cron")
    else
      install_cron_shim!(repo)
    end
  end

  defp install_cron_shim!(repo) do
    repo.query!("CREATE SCHEMA IF NOT EXISTS cron")

    repo.query!("""
    CREATE TABLE IF NOT EXISTS cron.job (
      jobid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      jobname text UNIQUE,
      schedule text,
      command text,
      active boolean DEFAULT true
    )
    """)
  end

  defp pg_cron_allowed?(repo) do
    config = repo.config()
    database = Keyword.fetch!(config, :database)

    {:ok, %{rows: [[cron_database]]}} =
      SQL.query(repo, "SHOW cron.database_name", [])

    cron_database == database
  rescue
    _ -> false
  end

  defp stamp_if_needed!(repo, version) do
    unless version in Ecto.Migrator.migrated_versions(repo) do
      Ecto.Migrator.up(repo, version, StampMigration, log: false)
    end
  end

  defp ensure_cleanup_job!(repo) do
    if cleanup_job_present?(repo) do
      :ok
    else
      definition = ArticleFlowCleanup.__pgflow_definition__()

      for sql <- PgFlow.JobCompiler.compile(definition, include_cron?: false) do
        repo.query!(sql)
      end
    end
  end

  defp cleanup_job_present?(repo) do
    %{rows: [[count]]} =
      repo.query!("SELECT count(*) FROM pgflow.flows WHERE flow_slug = 'article_flow_cleanup'")

    count > 0
  rescue
    _ -> false
  end

  defmodule StampMigration do
    @moduledoc false
    use Ecto.Migration

    @doc false
    @spec up() :: :ok
    def up, do: :ok

    @doc false
    @spec down() :: :ok
    def down, do: :ok
  end
end
