defmodule Mix.Tasks.Pgflow.Gen.HelpersMigrationTest do
  use ExUnit.Case, async: false

  alias Mix.Tasks.Pgflow.Gen.HelpersMigration, as: Helpers

  import ExUnit.CaptureIO

  @test_migrations_path "test/tmp/helpers_migrations"

  setup do
    File.rm_rf!(@test_migrations_path)
    File.mkdir_p!(@test_migrations_path)

    on_exit(fn ->
      File.rm_rf!(@test_migrations_path)
    end)

    :ok
  end

  describe "run/1" do
    test "generates migration file" do
      output =
        capture_io(fn ->
          Helpers.run([
            "--migrations-path",
            @test_migrations_path
          ])
        end)

      assert output =~ "Generated migration:"
      assert output =~ "add_pgflow_helpers.exs"
      assert output =~ "mix ecto.migrate"

      [migration_file] = File.ls!(@test_migrations_path)
      assert migration_file =~ ~r/^\d{14}_add_pgflow_helpers\.exs$/
    end

    test "generates migration with correct structure" do
      capture_io(fn ->
        Helpers.run([
          "--migrations-path",
          @test_migrations_path
        ])
      end)

      [migration_file] = File.ls!(@test_migrations_path)
      content = File.read!(Path.join(@test_migrations_path, migration_file))

      assert content == """
             defmodule Pgflow.Repo.Migrations.AddPgflowHelpers do
               @moduledoc \"\"\"
               Installs PgFlow extension SQL functions in the pgflow schema.

               Generated by: mix pgflow.gen.helpers_migration
               \"\"\"
               use Ecto.Migration

               def up do
                 PgFlow.HelpersMigration.up()
               end

               def down do
                 PgFlow.HelpersMigration.down()
               end
             end
             """
    end

    test "generates valid Elixir code" do
      capture_io(fn ->
        Helpers.run([
          "--migrations-path",
          @test_migrations_path
        ])
      end)

      [migration_file] = File.ls!(@test_migrations_path)
      migration_path = Path.join(@test_migrations_path, migration_file)

      {result, _} = Code.eval_file(migration_path)
      assert match?({:module, Pgflow.Repo.Migrations.AddPgflowHelpers, _, _}, result)
    end

    test "uses -p alias for migrations path" do
      capture_io(fn ->
        Helpers.run(["-p", @test_migrations_path])
      end)

      assert [_migration_file] = File.ls!(@test_migrations_path)
    end

    test "creates directory if it does not exist" do
      path = Path.join(@test_migrations_path, "nested/dir")
      refute File.exists?(path)

      capture_io(fn ->
        Helpers.run(["--migrations-path", path])
      end)

      assert File.exists?(path)
      assert [_migration_file] = File.ls!(path)
    end

    test "output includes setup instructions" do
      output =
        capture_io(fn ->
          Helpers.run([
            "--migrations-path",
            @test_migrations_path
          ])
        end)

      assert output =~ "Worker registration and lifecycle"
      assert output =~ "Flow input/output queries"
      assert output =~ "Stalled task recovery"
      assert output =~ "pgflow schema must already exist"
    end

    test "generates a version-aware upgrade when --from-version is supplied" do
      output =
        capture_io(fn ->
          Helpers.run([
            "--from-version",
            "4",
            "--migrations-path",
            @test_migrations_path
          ])
        end)

      [migration_file] = File.ls!(@test_migrations_path)
      content = File.read!(Path.join(@test_migrations_path, migration_file))

      assert output =~ "Generated migration:"
      assert migration_file =~ ~r/^\d{14}_upgrade_pgflow_helpers_to_v05\.exs$/
      assert content =~ "defmodule Pgflow.Repo.Migrations.UpgradePgflowHelpersToV05"
      assert content =~ "PgFlow.HelpersMigration.up(version: 5)"
      assert content =~ "PgFlow.HelpersMigration.down(version: 4)"
      refute content =~ "PgFlow.HelpersMigration.down()"
    end

    test "preserves -p for a version-aware upgrade" do
      capture_io(fn ->
        Helpers.run(["--from-version", "4", "-p", @test_migrations_path])
      end)

      [migration_file] = File.ls!(@test_migrations_path)
      assert migration_file =~ "upgrade_pgflow_helpers_to_v05.exs"
    end

    for invalid_version <- ["0", "-1", "5", "6", "invalid"] do
      @invalid_version invalid_version

      test "rejects source helper version #{@invalid_version} before writing" do
        assert_raise Mix.Error, fn ->
          Helpers.run([
            "--from-version",
            @invalid_version,
            "--migrations-path",
            @test_migrations_path
          ])
        end

        assert File.ls!(@test_migrations_path) == []
      end
    end

    for invalid_args <- [["unexpected"], ["--unknown-option"]] do
      @invalid_args invalid_args

      test "rejects invalid arguments #{inspect(@invalid_args)} before writing" do
        assert_raise Mix.Error, ~r/Invalid arguments for pgflow.gen.helpers_migration/, fn ->
          Helpers.run(@invalid_args ++ ["--migrations-path", @test_migrations_path])
        end

        assert File.ls!(@test_migrations_path) == []
      end
    end
  end
end
