defmodule Mix.Tasks.Pgflow.Gen.HelpersMigrationTest do
  use ExUnit.Case, async: false

  alias Mix.Tasks.Pgflow.Gen.HelpersMigration, as: Helpers

  import ExUnit.CaptureIO

  @test_migrations_path "test/tmp/helpers_migrations"

  setup do
    File.rm_rf!(@test_migrations_path)
    File.mkdir_p!(@test_migrations_path)

    on_exit(fn ->
      File.rm_rf!(@test_migrations_path)
    end)

    :ok
  end

  describe "run/1" do
    test "generates migration file" do
      output =
        capture_io(fn ->
          Helpers.run([
            "--migrations-path",
            @test_migrations_path
          ])
        end)

      assert output =~ "Generated migration:"
      assert output =~ "add_pgflow_helpers.exs"
      assert output =~ "mix ecto.migrate"

      [migration_file] = File.ls!(@test_migrations_path)
      assert migration_file =~ ~r/^\d{14}_add_pgflow_helpers\.exs$/
    end

    test "generates migration with correct structure" do
      capture_io(fn ->
        Helpers.run([
          "--migrations-path",
          @test_migrations_path
        ])
      end)

      [migration_file] = File.ls!(@test_migrations_path)
      content = File.read!(Path.join(@test_migrations_path, migration_file))

      assert content =~ "defmodule Pgflow.Repo.Migrations.AddPgflowHelpers"
      assert content =~ "use Ecto.Migration"
      assert content =~ "def up do"
      assert content =~ "PgFlow.HelpersMigration.up()"
      assert content =~ "def down do"
      assert content =~ "PgFlow.HelpersMigration.down()"
      assert content =~ "Generated by: mix pgflow.gen.helpers_migration"
    end

    test "generates valid Elixir code" do
      capture_io(fn ->
        Helpers.run([
          "--migrations-path",
          @test_migrations_path
        ])
      end)

      [migration_file] = File.ls!(@test_migrations_path)
      migration_path = Path.join(@test_migrations_path, migration_file)

      {result, _} = Code.eval_file(migration_path)
      assert match?({:module, Pgflow.Repo.Migrations.AddPgflowHelpers, _, _}, result)
    end

    test "uses -p alias for migrations path" do
      capture_io(fn ->
        Helpers.run(["-p", @test_migrations_path])
      end)

      assert length(File.ls!(@test_migrations_path)) == 1
    end

    test "creates directory if it does not exist" do
      path = Path.join(@test_migrations_path, "nested/dir")
      refute File.exists?(path)

      capture_io(fn ->
        Helpers.run(["--migrations-path", path])
      end)

      assert File.exists?(path)
      assert length(File.ls!(path)) == 1
    end

    test "output includes setup instructions" do
      output =
        capture_io(fn ->
          Helpers.run([
            "--migrations-path",
            @test_migrations_path
          ])
        end)

      assert output =~ "Worker registration and lifecycle"
      assert output =~ "Flow input/output queries"
      assert output =~ "Stalled task recovery"
      assert output =~ "pgflow schema must already exist"
    end
  end
end
