defmodule Mix.Tasks.Pgflow.Gen.JobMigrationTest do
  use ExUnit.Case, async: false

  alias Mix.Tasks.Pgflow.Gen.JobMigration, as: GenJob

  import ExUnit.CaptureIO

  @test_migrations_path "test/tmp/job_migrations"

  setup do
    File.rm_rf!(@test_migrations_path)
    File.mkdir_p!(@test_migrations_path)

    on_exit(fn ->
      File.rm_rf!(@test_migrations_path)
    end)

    :ok
  end

  describe "run/1" do
    test "generates migration for a valid job module" do
      output =
        capture_io(fn ->
          GenJob.run([
            "PgFlow.TestJobs.SimpleJob",
            "--migrations-path",
            @test_migrations_path
          ])
        end)

      assert output =~ "Generated migration:"
      assert output =~ "simple_job"
      assert output =~ "mix ecto.migrate"
      assert output =~ "flow_type = 'job'"

      [migration_file] = File.ls!(@test_migrations_path)
      assert migration_file =~ "_compile_simple_job.exs"

      migration_content = File.read!(Path.join(@test_migrations_path, migration_file))

      assert migration_content =~ "defmodule PgFlow.Repo.Migrations.CompileSimpleJob"
      assert migration_content =~ "use Ecto.Migration"
      assert migration_content =~ "def up do"
      assert migration_content =~ "def down do"
      assert migration_content =~ "SELECT pgflow.create_flow('simple_job'"
      assert migration_content =~ "SELECT pgflow.add_step('simple_job', 'simple_job'"
      assert migration_content =~ "UPDATE pgflow.flows SET flow_type = 'job'"
      assert migration_content =~ "DELETE FROM pgflow.flows WHERE flow_slug = 'simple_job'"
      assert migration_content =~ "SELECT pgmq.drop_queue('simple_job')"
    end

    test "generates migration for a job with custom options" do
      capture_io(fn ->
        GenJob.run([
          "PgFlow.TestJobs.EmailJob",
          "--migrations-path",
          @test_migrations_path
        ])
      end)

      [migration_file] = File.ls!(@test_migrations_path)
      migration_content = File.read!(Path.join(@test_migrations_path, migration_file))

      assert migration_content =~ "create_flow('email_job'"
      assert migration_content =~ "add_step('email_job', 'email_job'"
      assert migration_content =~ "flow_type = 'job'"
    end

    test "raises error when no module argument provided" do
      assert_raise Mix.Error, ~r/Missing job module argument/, fn ->
        capture_io(fn ->
          GenJob.run(["--migrations-path", @test_migrations_path])
        end)
      end
    end

    test "raises error when module does not exist" do
      assert_raise Mix.Error, ~r/could not be loaded/, fn ->
        capture_io(fn ->
          GenJob.run([
            "NonExistent.JobModule",
            "--migrations-path",
            @test_migrations_path
          ])
        end)
      end
    end

    test "raises error when module is not a job" do
      assert_raise Mix.Error, ~r/is not a PgFlow job/, fn ->
        capture_io(fn ->
          GenJob.run([
            "PgFlow.FlowCompiler",
            "--migrations-path",
            @test_migrations_path
          ])
        end)
      end
    end

    test "raises error when module is a flow, not a job" do
      assert_raise Mix.Error, ~r/is not a PgFlow job/, fn ->
        capture_io(fn ->
          GenJob.run([
            "PgFlow.TestFlows.SimpleFlow",
            "--migrations-path",
            @test_migrations_path
          ])
        end)
      end
    end
  end

  describe "generated migration content" do
    test "includes proper module documentation" do
      capture_io(fn ->
        GenJob.run([
          "PgFlow.TestJobs.SimpleJob",
          "--migrations-path",
          @test_migrations_path
        ])
      end)

      [migration_file] = File.ls!(@test_migrations_path)
      migration_content = File.read!(Path.join(@test_migrations_path, migration_file))

      assert migration_content =~ "@moduledoc"
      assert migration_content =~ "Compiles the 'simple_job' job definition"
      assert migration_content =~ "Generated by: mix pgflow.gen.job_migration"
    end

    test "generates valid Elixir code" do
      capture_io(fn ->
        GenJob.run([
          "PgFlow.TestJobs.SimpleJob",
          "--migrations-path",
          @test_migrations_path
        ])
      end)

      [migration_file] = File.ls!(@test_migrations_path)
      migration_path = Path.join(@test_migrations_path, migration_file)

      {result, _} = Code.eval_file(migration_path)
      assert match?({:module, PgFlow.Repo.Migrations.CompileSimpleJob, _, _}, result)
    end
  end
end
