defmodule PgFlow.Repo.Migrations.CompileSendEmail do
  @moduledoc """
  Compiles the 'send_email' job definition into the database.

  This migration creates:
  - The flow record in pgflow.flows (with flow_type = 'job')
  - The PGMQ queue for this job
  - The step definition

  Generated by: mix pgflow.gen.job_migration
  """
  use Ecto.Migration

  def up do
    execute "SELECT pgflow.create_flow('send_email', 3, 1, 30)"

    execute "SELECT pgflow.add_step('send_email', 'deliver', ARRAY[]::text[], 3, 1, 30, NULL, 'single')"

    execute "UPDATE pgflow.flows SET flow_type = 'job' WHERE flow_slug = 'send_email'"
  end

  def down do
    execute "DELETE FROM pgflow.deps WHERE flow_slug = 'send_email'"
    execute "DELETE FROM pgflow.steps WHERE flow_slug = 'send_email'"
    execute "DELETE FROM pgflow.flows WHERE flow_slug = 'send_email'"
    execute "SELECT pgmq.drop_queue('send_email')"
  end
end
