defmodule PgFlow.Repo.Migrations.CompileArticleFlow do
  @moduledoc """
  Compiles the 'article_flow' flow definition into the database.

  This migration creates:
  - The flow record in pgflow.flows
  - The PGMQ queue for this flow
  - All step definitions in pgflow.steps

  Generated by: mix pgflow.gen.flow_migration
  """
  use Ecto.Migration

  def up do
    execute "SELECT pgflow.create_flow('article_flow', 3, 5, 120)"

    execute "SELECT pgflow.add_step('article_flow', 'fetch_article', ARRAY[]::text[], 3, 5, 120, NULL, 'single')"

    execute "SELECT pgflow.add_step('article_flow', 'convert_to_markdown', ARRAY['fetch_article']::text[], 3, 5, 120, NULL, 'single')"

    execute "SELECT pgflow.add_step('article_flow', 'summarize', ARRAY['convert_to_markdown']::text[], 3, 5, 120, NULL, 'single')"

    execute "SELECT pgflow.add_step('article_flow', 'extract_keywords', ARRAY['convert_to_markdown']::text[], 3, 5, 120, NULL, 'single')"

    execute "SELECT pgflow.add_step('article_flow', 'publish', ARRAY['summarize', 'extract_keywords']::text[], 3, 5, 120, NULL, 'single')"
  end

  def down do
    execute "DELETE FROM pgflow.deps WHERE flow_slug = 'article_flow'"
    execute "DELETE FROM pgflow.steps WHERE flow_slug = 'article_flow'"
    execute "DELETE FROM pgflow.flows WHERE flow_slug = 'article_flow'"
    execute "SELECT pgmq.drop_queue('article_flow')"
  end
end
