defmodule PgFlow.Repo.Migrations.CompileArticleFlowCleanup do
  @moduledoc """
  Compiles the 'article_flow_cleanup' job definition into the database.

  This migration creates:
  - The flow record in pgflow.flows (with flow_type = 'job')
  - The PGMQ queue for this job
  - The step definition

  Generated by: mix pgflow.gen.job_migration
  """
  use Ecto.Migration

  def up do
    execute "SELECT pgflow.create_flow('article_flow_cleanup', 3, 1, 60)"

    execute "SELECT pgflow.add_step('article_flow_cleanup', 'article_flow_cleanup', ARRAY[]::text[], 3, 1, 60, NULL, 'single')"

    execute "SELECT cron.schedule('pgflow:article_flow_cleanup', '@hourly', $$SELECT pgflow.start_flow('article_flow_cleanup', '{\"retention_hours\":24}'::jsonb)$$)"

    execute "UPDATE pgflow.flows SET flow_type = 'job' WHERE flow_slug = 'article_flow_cleanup'"
  end

  def down do
    execute "SELECT cron.unschedule('pgflow:article_flow_cleanup')"
    execute "DELETE FROM pgflow.deps WHERE flow_slug = 'article_flow_cleanup'"
    execute "DELETE FROM pgflow.steps WHERE flow_slug = 'article_flow_cleanup'"
    execute "DELETE FROM pgflow.flows WHERE flow_slug = 'article_flow_cleanup'"
    execute "SELECT pgmq.drop_queue('article_flow_cleanup')"
  end
end
