defmodule PgflowDemo.Repo.Migrations.InstallPgmq do
  @moduledoc """
  Installs pgmq via the bundled SQL file.

  Generated by: `mix pgflow.gen.pgmq_migration`
  SQL source:   priv/pgflow/pgmq/pgmq-1.11.0.sql

  The pgmq SQL contains many top-level statements. Postgrex rejects
  multi-statement prepared queries (`42601 syntax_error`), so we use
  `PgFlow.Sql.Splitter` to split the SQL into single statements and
  run each via `execute/1`. This keeps the migration portable — no
  `psql` on PATH required at migrate time, which matters for slim
  release images and managed CI runners.

  The splitter is dollar-quote aware, so plpgsql function bodies with
  internal semicolons (`BEGIN ... END;` inside `$$ ... $$`) split
  correctly.
  """
  use Ecto.Migration

  @disable_ddl_transaction true
  @disable_migration_lock true

  @otp_app :pgflow_demo
  @sql_relpath "pgflow/pgmq/pgmq-1.11.0.sql"

  def up do
    sql_path = Path.join(:code.priv_dir(@otp_app), @sql_relpath)

    sql_path
    |> File.read!()
    |> PgFlow.Sql.Splitter.split()
    |> Enum.each(&execute/1)
  end

  def down do
    execute("DROP SCHEMA IF EXISTS pgmq CASCADE")
  end
end
