defmodule PgFlow.Repo.Migrations.CompileOnboardingFlow do
  @moduledoc """
  Compiles the 'onboarding_flow' flow definition into the database.

  This migration creates:
  - The flow record in pgflow.flows
  - The PGMQ queue for this flow
  - All step definitions in pgflow.steps

  Generated by: mix pgflow.gen.flow_migration
  """
  use Ecto.Migration

  def up do
    execute "SELECT pgflow.create_flow('onboarding_flow', 3, 1, 30)"

    execute "SELECT pgflow.add_step('onboarding_flow', 'create_account', ARRAY[]::text[], 3, 1, 30, NULL, 'single')"

    execute "SELECT pgflow.add_step('onboarding_flow', 'setup_premium', ARRAY['create_account']::text[], 3, 1, 30, NULL, 'single', required_input_pattern => '{\"create_account\":{\"plan\":\"premium\"}}'::jsonb, when_unmet => 'skip-cascade')"

    execute "SELECT pgflow.add_step('onboarding_flow', 'activate_perk', ARRAY['setup_premium']::text[], 3, 1, 30, NULL, 'single')"

    execute "SELECT pgflow.add_step('onboarding_flow', 'send_welcome', ARRAY['create_account']::text[], 1, 1, 30, NULL, 'single', when_exhausted => 'skip')"

    execute "SELECT pgflow.add_step('onboarding_flow', 'finish', ARRAY['create_account']::text[], 3, 1, 30, NULL, 'single')"
  end

  def down do
    execute "DELETE FROM pgflow.deps WHERE flow_slug = 'onboarding_flow'"
    execute "DELETE FROM pgflow.steps WHERE flow_slug = 'onboarding_flow'"
    execute "DELETE FROM pgflow.flows WHERE flow_slug = 'onboarding_flow'"
    execute "SELECT pgmq.drop_queue('onboarding_flow')"
  end
end
