defmodule PgFlow.Repo.Migrations.CompileApprovalFlow do
  @moduledoc """
  Compiles the 'approval_flow' flow definition into the database.

  This migration creates:
  - The flow record in pgflow.flows
  - The PGMQ queue for this flow
  - All step definitions in pgflow.steps

  Generated by: mix pgflow.gen.flow_migration
  """
  use Ecto.Migration

  def up do
    execute "SELECT pgflow.create_flow('approval_flow', 3, 1, 30)"
    execute "SELECT pgflow.add_step('approval_flow', 'create_order', ARRAY[]::text[], 3, 1, 30, NULL, 'single')"
    execute "SELECT pgflow.add_step('approval_flow', 'await_approval', ARRAY['create_order']::text[], 1, 1, 30, NULL, 'single')"
    execute "SELECT pgflow.add_step('approval_flow', 'charge', ARRAY['await_approval']::text[], 3, 1, 30, NULL, 'single')"
  end

  def down do
    execute "DELETE FROM pgflow.deps WHERE flow_slug = 'approval_flow'"
    execute "DELETE FROM pgflow.steps WHERE flow_slug = 'approval_flow'"
    execute "DELETE FROM pgflow.flows WHERE flow_slug = 'approval_flow'"
    execute "SELECT pgmq.drop_queue('approval_flow')"
  end
end
