defmodule PgflowDemo.Repo.Migrations.SetupPgflow do
  @moduledoc """
  Installs pgflow's core schema + Elixir helper functions.

  Generated by: `mix pgflow.setup`

  SQL sources (vendored inside pgflow):
    - priv/pgflow_core/sql/versions/v01/v01_up.sql       (core: flows, runs, steps, workers, step_tasks, step_states, deps)
    - priv/pgflow_helpers/sql/versions/v01/v01_up.sql    (Elixir-binding RPC helpers)

  `PgFlow.Migration.up/0` runs via EctoEvolver with statement-level
  splitting — the V01 core bundle contains 138 statements and
  Postgrex rejects multi-statement queries (error `42601`).
  `PgFlow.HelpersMigration.up/0` adds Elixir-binding SQL functions
  (`flow_exists`, `register_worker`, `get_flow_input`, ...) that the
  library's query layer calls via RPC.

  Idempotent: rerun is a no-op via EctoEvolver's tracking comment on
  `pgflow.pgflow_version`.

  Prerequisites (applied as earlier migrations):
    1. Postgres extensions — `mix pgflow.gen.postgres_extensions_migration`
    2. pgmq schema + functions — `mix pgflow.gen.pgmq_migration` (or a
       native `CREATE EXTENSION pgmq` on Supabase/atlas-postgres-pgflow)
  """
  use Ecto.Migration

  def up do
    PgFlow.Migration.up()
    PgFlow.HelpersMigration.up()
  end

  def down do
    PgFlow.HelpersMigration.down()
    PgFlow.Migration.down()
  end
end
