defmodule PgflowDemo.Repo.Migrations.InstallExtensions do
  @moduledoc """
  Installs Postgres extensions required by pgflow.

  Generated by: `mix pgflow.gen.postgres_extensions_migration`

  Extensions:
    - citext     — case-insensitive text columns
    - pg_trgm    — trigram indexes (dashboard slug search)
    - pgcrypto   — `gen_random_uuid()` for primary keys
    - pg_cron    — scheduled flow/job support

    pg_cron requires TWO server-level settings in `postgresql.conf`:
    - `shared_preload_libraries = 'pg_cron'`  (add + restart Postgres)
    - `cron.database_name = '<your_app_db>'` (pg_cron's metadata lives
      in exactly one DB; defaults to `postgres`. If your app DB isn't
      `postgres`, set this or install pg_cron against `postgres`
      instead — cron functions will only exist in the configured DB).

  Supported on Neon, AWS RDS (PG 12.5+), Aurora (PG 12.6+), and
  Supabase — each with its own setup path (parameter groups, API
  calls, etc.). On hosts that don't support pg_cron, regenerate
  with `mix pgflow.gen.postgres_extensions_migration --no-cron`.

  `@disable_ddl_transaction true` is set because `CREATE EXTENSION` can't
  run inside a migration transaction on some Postgres distributions.
  `@disable_migration_lock true` is set for the same reason.

  On hosts with native pgmq (Supabase, atlas-postgres-pgflow), hand-add
  `execute("CREATE EXTENSION IF NOT EXISTS pgmq")` here instead of
  running `mix pgflow.gen.pgmq_migration`.
  """
  use Ecto.Migration

  @disable_ddl_transaction true
  @disable_migration_lock true

  def up do
    execute("CREATE EXTENSION IF NOT EXISTS citext")
    execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    execute("CREATE EXTENSION IF NOT EXISTS pg_cron")
  end

  def down do
    execute("DROP EXTENSION IF EXISTS pg_cron")
    execute("DROP EXTENSION IF EXISTS pgcrypto")
    execute("DROP EXTENSION IF EXISTS pg_trgm")
    execute("DROP EXTENSION IF EXISTS citext")
  end
end
